// This file is generated by GoAdmin CLI adm.
package tables

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// Generators is a map of table models.
//
// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// example end
//
var Generators = map[string]table.Generator{
	"twitter_account":          GetTwitterAccountTable,
	"twitter_account_daily":    GetTwitterAccountDailyLog,
	"twitter_account_realtime": GetTwitterAccountRealTime,
	"tweets":                   GetTweetsTable,
	"telegram_group":           GetTelegramGroupTable,
	"telegram_group_daily":     GetTelegramGroupDailyTable,
	"telegram_group_realtime":  GetTelegramGroupRealTimeTable,
	"telegram_member":          GetTelegramGroupMemberTable,
	"discord_guild":            GetDiscordGuildTable,
	"discord_guild_realtime":   GetDiscordGuildRealTimeTable,
	"discord_guild_daily":      GetDiscordGuildDailyTable,
	"discord_guild_member":     GetDiscordGuildMemberTable,
	"discord_channel":          GetDiscordChannelTable,
	"discord_channel_realtime": GetDiscordChannelRealTimeTable,
	"discord_channel_daily":    GetDiscordGuildChannelDailyTable,
	"wallet_daily":             GetWalletDailyDataTable,
}
